### ISSUE TITLE
Multiple clickovers do not respect "click anywhere else to close"

### ISSUE THREAD

**Issue by cdepair** [lecar-red/bootstrapx-clickover#2]
Steps: 

If you have multiple clickover elements on the screen, click on one then click on another.

Expected Behavior:

First click over disappears, second one appears

Actual Behavior:

First click over does not disappear, leaving multiple click overs appearing

**Comment by lecar-red** [comment]
Thanks for finding this.

Interesting, let me look and see what i can do. I bet it should be an option to turn off or on. Any thoughts on that?

**Comment by cdepair** [comment]
Agreed. Some times you might want to have multiple clickovers open, sometimes you might want to limit it to one.

**Comment by kdrdgn** [comment]
Hi lecar-red, thanks to your great extension, i really need to it, but i have same problem with cdepair, i want to have limit it to show one of them. what is your advice about this situation?

**Comment by lecar-red** [comment]
a possible quick hack would be to grab them all with:

``` javascript
$('.popover').hide();
```

But after looking at that i think it might close the one you've just opened :(

I suspect that might require a click handler on your clickover element which isn't too pretty. I'm going to spend a little time looking at ways to add this option to the library this week. I don't think it will require much code but probably a bit of thought on how to manage the others.

**Comment by lecar-red** [comment]
my question for both of you, should this be the default behavior?

**Comment by kdrdgn** [comment]
i think it should, because of this is a routin behaviour.

additional $('.popover').hide(); does not executed another clicekry owner elements. so add this code your in your clickery plugin and change this.show() instead of this.toggle();

**Comment by lecar-red** [comment]
Thanks for your input.

I found that bug yesterday. I switched all of the internal 'hide' calls over to using clickery handler (poorly named in hindsight). I ran into issue with the onHidden event handler. The newest version on github should have those changes.

I think what I will do is since I added a smart data api attribute, i'll have the opening clickover close all others unless the allow_multiple flag is set. Unless you can think of a better option name (i'd love any input on this). I plan to update the code this afternoon or tomorrow morning (assuming I have time).

**Comment by kdrdgn** [comment]
Hi lecar,

'allow_multiple' fair enough. This option name assumes show 1 popover each click. By the way, i guess i found another bug maybe i'am wrong.

I have a button group( radio buttons ) in my tip and i use data api  `<div class="btn-group" data-toggle="buttons-radio">`

``` javascript
this.tip().on('click', function(e) { e.stopPropagation(); });
```

 this line cancel all click events in tip elements. So another bootstrap plugin can not initialize over data api.

**Comment by lecar-red** [comment]
stop that :)

I ran into that too, i need to figure out a way to stop propagation to the hide handler when clicked inside the clickover but allow the rest to go through. i have a note in there that I need to check the target of the event and only return false for that.

i'll take a look at a fix for that today too. I've been putting it off since i had a work around of attaching those type of events inside the 'onShown' event. But since you ran into it too i'll take a look. 

if you have a bit of a test chunk of code that would be very helpful, probably best to start a new issue as well.

**Comment by kdrdgn** [comment]
haha :) ok, ok

i read your blog and i think, your are walking front of me about some issues ;) 
i saw your TODO comments in there. thnx for fix.

**Comment by kdrdgn** [comment]
Hi lecar, 

normally i have to pull request for changes but i use your previous versions. i inspired from Ben Alman's clickoutside events, and add this code instead of 

``` javascript
that = this;
$('body').one( this.attr.click_event_ns,function(e){
  if (!that.tip().has(event.target).length ) { that.hide(); }
});
```

and comment out 

``` javascript
//this.tip().on('click', function(e) { e.stopPropagation(); } );
```

what do you think about this solution?

**Comment by lecar-red** [comment]
ooh, let me give it a try, i was having trouble coming up with something that was working

**Comment by lecar-red** [comment]
i made a couple of tweaks to the code above but otherwise it worked great. Also, i added support to close all other clickovers when opening a new one. I think that maybe global close one a clickover should stop it from being closed by others. I'm going to think about that a bit, i'm not 100% sure that is really right. Probably best to wait for that occasion to arise to figure it out.

**Comment by lecar-red** [comment]
hi cdepair, did the last round of changes fix this issue for you?
